// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: inserts.sql

package database

import (
	"context"
)

const insertReactionTime = `-- name: InsertReactionTime :one
INSERT INTO reaction_times (time, user_id, tms_insert)
VALUES ($1, $2, NOW())
RETURNING id, time, tms_insert, user_id
`

type InsertReactionTimeParams struct {
	Time   int64
	UserID int64
}

func (q *Queries) InsertReactionTime(ctx context.Context, arg InsertReactionTimeParams) (ReactionTime, error) {
	row := q.db.QueryRow(ctx, insertReactionTime, arg.Time, arg.UserID)
	var i ReactionTime
	err := row.Scan(
		&i.ID,
		&i.Time,
		&i.TmsInsert,
		&i.UserID,
	)
	return i, err
}
