// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ReactionTime struct {
	ID        int64
	Time      int64
	TmsInsert pgtype.Timestamp
	UserID    int64
}

type User struct {
	ID   int64
	Name string
}
